export { useCodeInput } from 'use-code-input'
export { useLengthContext, useSelectionContext } from './components/Context'
export { CodeInput } from './components/CodeInput'
export * as RCI from './components/RCI'
export type { SegmentProps } from './types/SegmentProps'
export { getSegmentCssWidth } from './utils/getSegmentCssWidth'