name: Build

on: [push, pull_request]

jobs:
  release:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        uses: pnpm/action-setup@v4
        with: { run_install: true }

      - name: Run build
        run: pnpm run build

      - name: List installed versions
        run: pnpm --recursive list react react-dom @types/react @types/react-dom

      - name: Typecheck (react@18)
        run: pnpm run typecheck

      - name: Lint
        run: pnpm run format -l

      - name: Check Git Status
        run: git status --porcelain

      - name: Update to latest react
        run: pnpm --recursive update --latest react react-dom @types/react @types/react-dom

      - name: List installed versions
        run: pnpm --recursive list react react-dom @types/react @types/react-dom

      - name: Typecheck (react@latest)
        run: pnpm run typecheck
